env:
  global:
    - secure: oXc5B0QaYC05GZ9imgUHpsBnCb4fIJpLjAtqzLm8r6d7xGWy3fToYlD6oMMsGmG+SXWnQNcoS5/R3vhZLpurGeTtPEGJlZCGxtDbAh7rOeh/GJf2PVehAkgRLdVO1mxz8GFoMoTrjTDZIpilZIApg56hRScnX8aK6YvYhN72wOo=
os:
  - linux
  - osx
language: rust
rust:
  - nightly
#  - beta
#  - stable
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/elfutils-$ElfUtilsVersion
before_install:
    - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/dependency_versions.sh
    - . dependency_versions.sh
script:
  - export RUST_TEST_THREADS=1
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/build_and_run_tests.sh | bash
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/after_success.sh | bash
