[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "http://docs.maidsafe.net/crust/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "crust"
readme = "README.md"
repository = "https://github.com/maidsafe/crust"
version = "0.16.2"

[dependencies]
byteorder = "~0.5.3"
c_linked_list = "~1.1.0"
config_file_handler = "~0.3.1"
crossbeam = "~0.2.9"
igd = "~0.5.0"
libc = "~0.2.14"
log = "~0.3.6"
maidsafe_utilities = "~0.8.0"
net2 = "~0.2.26"
quick-error = "~1.1.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
sodiumoxide = "=0.0.10"
tmp_mio = "~0.5.2"
unwrap = "~1.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "~0.2"

[dependencies.clippy]
optional = true
version = "~0.0.79"
