[package]
name = "crust"
version = "0.0.51"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/crust/crust"
repository = "https://github.com/dirvine/crust"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
docopt = "*"
time = "*"
sodiumoxide = "0.0.4"
rand = "*"

[[example]]
name = "simple_sender"
path = "examples/simple_sender.rs"
test = false
bench = false

[[example]]
name = "simple_receiver"
path = "examples/simple_receiver.rs"
test = false
bench = false

[[example]]
name = "crust_node"
path = "examples/crust_node.rs"
test = false
bench = false
