[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Peer-to-peer networking library. Automatically reconnect and manage connections."
documentation = "https://docs.rs/crust"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "crust"
readme = "README.md"
repository = "https://github.com/maidsafe/crust"
version = "0.28.1"

[[example]]
name = "connect"
path = "examples/connect.rs"

[[example]]
name = "exchange_data"
path = "examples/exchange_data.rs"

[dependencies]
bytes = "0.4"
config_file_handler = "0.8.0"
env_logger = "0.4.3"
future-utils = "0.5.0"
futures = "0.1.17"
get_if_addrs = "0.4.0"
igd = "0.6.0"
log = "0.3.8"
maidsafe_utilities = "0.14.0"
maplit = "0.1.5"
net-literals = "0.1"
net2 = "0.2.31"
notify = "4.0.1"
quick-error = "1.2.0"
rand = "0.3.17"
rand_derive = "0.3.1"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
tiny-keccak = "1.3"
tokio-core = "0.1.10"
tokio-io = "0.1.3"
unwrap = "1.1"
void = "1.0.2"

[dependencies.p2p]
git = "https://github.com/ustulation/p2p"

[dev-dependencies]
hamcrest = "0.1.5"
